### ISSUE TITLE
Always delete artifacts after apply job has started

### ISSUE THREAD

**Issue by gavanlamb** [cupel-co/workflows#5]
```yaml
      - name: 'Delete ${{ inputs.artifact-name }}'
        uses: cupel-co/actions/.github/actions/artifact/delete@v0.19.3
        with:
          name: '${{ inputs.artifact-name }}'
```
